# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [4]:
import numpy as np
print("version:", np.version)
np.show_config()

version: <module 'numpy.version' from '/usr/local/lib/python3.11/dist-packages/numpy/version.py'>
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /projec

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [6]:
arr2 = np.zeros(9, dtype = np.int64)
arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [7]:
arr3 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr3_size = arr3.size # 10
arr3_itemsize = arr3.itemsize # 8

In [8]:
arr3_size

10

In [9]:
arr3.itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [10]:
info_add = np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [11]:
info_add

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [12]:
arr4 = np.zeros(12, np.int8)
arr4[5] = 1
arr4


array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int8)

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [13]:
arr5 = np.arange(20, 60)
arr5

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [14]:
arr6 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr6[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [15]:
arr7 = np.arange(12, 21).reshape(3,3)
arr7

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [16]:
arr7 = np.array([3, 7, 0, 0, 9, 0])
np.nonzero(arr7)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [17]:
arr8 = np.random.random((2, 2, 2))
arr8

array([[[0.57803721, 0.13873552],
        [0.08921254, 0.03504755]],

       [[0.84719311, 0.76209843],
        [0.10655687, 0.73099485]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [18]:
arr9 = np.random.randn(9, 9)
arr9.min()


np.float64(-1.8094138463600762)

In [19]:
arr9.max()

np.float64(2.6631839095129086)

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [20]:
0 * np.nan # nan
np.nan == np.nan # False
np.inf > np.nan #False
np.nan - np.nan # nan
np.nan in set([np.nan]) # True
0.7 == 7 * 0.1 # False

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [21]:
a = np.arange(18).reshape(6, 3)
b = np.arange(12).reshape(3, 4)
c = np.dot(a,b)
c

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218],
       [164, 203, 242, 281],
       [200, 248, 296, 344]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [22]:
# javob
9

9

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [23]:
a = np.array([1, 2])
b = np.array([4, 5])

np.greater(a, b) # a > b
np.greater_equal(a, b) # a >= b
np.less(a, b) # a < b
np.less_equal(a, b) # a <= b

array([ True,  True])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [24]:
a = np.array(0) / np.array(0) # nan
a

/tmp/ipython-input-24-3316460694.py:1: RuntimeWarning: invalid value encountered in divide
  a = np.array(0) / np.array(0) # nan


np.float64(nan)

In [25]:
b = np.array(0) // np.array(0) # 0
b

/tmp/ipython-input-25-1617694088.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  b = np.array(0) // np.array(0) # 0


np.int64(0)

In [26]:
np.array([np.nan]).astype(int).astype(float) # array([-9.22337204e+18])

/tmp/ipython-input-26-3743835776.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float) # array([-9.22337204e+18])


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [27]:
arr1 = np.array([1, 8, 11, 14, 5, 3, 10])
arr2 = np.array([9, 3, 22, 1, 18, 4, 2])
arr3 = np.intersect1d(arr1, arr2)
arr3

array([1, 3])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [28]:
arr = np.random.randn(5,5)
arr[arr>0] % 1
np.floor(arr[arr>0])
np.trunc(arr[arr>0])
arr[arr>0].astype(np.int64)

arr

array([[ 0.8795105 , -0.81698697,  0.25713555,  1.23712651, -0.38205603],
       [-0.39236432,  1.23285436,  0.41544804,  1.33121442,  0.42942147],
       [-1.16767118, -0.7388343 ,  0.10942065, -1.45016312,  2.51162175],
       [ 1.13438684, -0.25778242,  1.00512409,  0.10147327,  1.09168717],
       [-1.59286436,  0.31986157,  1.18973964, -0.37906534,  0.30011175]])

In [29]:
arr[arr>0]

array([0.8795105 , 0.25713555, 1.23712651, 1.23285436, 0.41544804,
       1.33121442, 0.42942147, 0.10942065, 2.51162175, 1.13438684,
       1.00512409, 0.10147327, 1.09168717, 0.31986157, 1.18973964,
       0.30011175])

In [30]:
np.floor(arr[arr>0])

array([0., 0., 1., 1., 0., 1., 0., 0., 2., 1., 1., 0., 1., 0., 1., 0.])

In [31]:
np.trunc(arr[arr>0])

array([0., 0., 1., 1., 0., 1., 0., 0., 2., 1., 1., 0., 1., 0., 1., 0.])

In [32]:
arr[arr>0].astype(np.int64)

array([0, 0, 1, 1, 0, 1, 0, 0, 2, 1, 1, 0, 1, 0, 1, 0])

In [33]:
(arr[arr>0] % 1).astype(np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [34]:
arr = np.random.randint(0, 3, size=(3,3))

arr

array([[2, 0, 1],
       [2, 1, 2],
       [2, 0, 0]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [35]:
arr = np.random.randn(10)
arr.sort()
np.sort(arr)

arr

array([-1.82023969, -0.93215949, -0.41951579, -0.38880552, -0.37606342,
        0.21142629,  0.51323806,  0.78052606,  0.95014172,  1.45520203])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [36]:
A = np.random.randn(2, 2)
B = np.random.randn(2, 2)

In [37]:
A

array([[ 3.15865408e-04, -5.33500401e-01],
       [ 1.22482727e+00, -8.51054385e-01]])

In [38]:
B

array([[-0.00870183,  0.70653277],
       [-0.11411032,  0.98054939]])

In [39]:
np.allclose(A, B)

False

In [40]:
np.array_equal(A, B)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [41]:
a = np.random.randn(6, 3)
b = np.random.randn(3, 4)
c = np.dot(a, b)
c

array([[ 0.26115866,  1.68174407,  1.90445227, -2.1131027 ],
       [-0.12524852,  1.72980512,  1.37482912, -0.72560014],
       [-0.39824142,  1.44039895,  0.83514207,  1.78397417],
       [ 1.25614579, -1.25162862,  1.11169291,  0.15879955],
       [ 0.19293907,  0.15219355,  0.54195034,  0.41465322],
       [ 0.17347805, -0.67895137, -0.2389484 ,  1.03306614]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [42]:
arr = np.random.rand(5)
arr

array([0.24542339, 0.17890466, 0.84202518, 0.86663736, 0.2120177 ])

In [43]:
max_indeks = np.argmax(arr)
max_indeks

np.int64(3)

In [44]:
arr[max_indeks] = 0

arr

array([0.24542339, 0.17890466, 0.84202518, 0.        , 0.2120177 ])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [45]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [46]:
np.arange('2016-01', '2016-02', dtype='datetime64[D]')

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [47]:
arr = np.random.randn(5, 5)
positive_numbers = arr[arr > 0]
positive_numbers % 1
np.floor(positive_numbers)
positive_numbers.astype(int)
np.trunc(positive_numbers)

array([0., 0., 0., 0., 1., 0., 1., 2., 1., 0., 0., 1., 0.])

In [48]:
arr

array([[ 0.17764089, -1.54040217, -0.47081409, -0.41598017,  0.05596971],
       [ 0.05880688, -0.88925868, -1.66328783,  0.77683382,  1.33486815],
       [-0.77618624, -0.89328345, -0.47630823,  0.27494828,  1.43397921],
       [-0.4584823 , -0.35495529,  2.10474201,  1.36247586,  0.26731692],
       [ 0.40210901, -1.05066244,  1.02295544, -0.50532833,  0.58454366]])

In [49]:
positive_numbers

array([0.17764089, 0.05596971, 0.05880688, 0.77683382, 1.33486815,
       0.27494828, 1.43397921, 2.10474201, 1.36247586, 0.26731692,
       0.40210901, 1.02295544, 0.58454366])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [50]:
arr = [np.array([1, 5, 8, 6, 2]), np.array([4, 2, 10, 5, 9]), np.array([8, 16, 7, 1, 12])]
np.add.reduce(arr)

array([13, 23, 25, 12, 23])

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [51]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
new_vector = np.zeros(len(arr) + 3*(len(arr)-1))
new_vector[::4] = arr

new_vector

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [52]:
from numpy.lib.stride_tricks import as_strided

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
window_size = 4
stride = a.itemsize
b = as_strided(a, shape=(len(a) - window_size + 1, window_size), strides=(stride, stride))
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [53]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
np.bincount(x).argmax()

np.int64(1)

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`